-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 18:02:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema peliculasappdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema peliculasappdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peliculasappdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `peliculasappdb` ;

-- -----------------------------------------------------
-- Table `peliculasappdb`.`Peliculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasappdb`.`Peliculas` ;

CREATE TABLE IF NOT EXISTS `peliculasappdb`.`Peliculas` (
  `idPelicula` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(65) NOT NULL,
  `anyo` INT NOT NULL,
  `duracion` INT NOT NULL, 
  `pais` VARCHAR(2) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `sinopsis` VARCHAR(1000) NOT NULL,
  `imagen` VARCHAR(350) NULL,
  PRIMARY KEY (`idPelicula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculasappdb`.`Actores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasappdb`.`Actores` ;

CREATE TABLE IF NOT EXISTS `peliculasappdb`.`Actores` (
  `idActor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fcNacimiento` DATE NOT NULL,
  `pais` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idActor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosalumnosdb`.`Peliculas_has_Actores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasappdb`.`Peliculas_has_Actores` ;

CREATE TABLE IF NOT EXISTS `peliculasappdb`.`Peliculas_has_Actores` (
  `Peliculas_idPelicula` INT NOT NULL,
  `Actores_idActor` INT NOT NULL,
  PRIMARY KEY (`Peliculas_idPelicula`, `Actores_idActor`),
  INDEX `fk_Peliculas_has_Actores_Actores1_idx` (`Actores_idActor` ASC) VISIBLE,
  INDEX `fk_Peliculas_has_Actores_Peliculas_idx` (`Peliculas_idPelicula` ASC) VISIBLE,
  CONSTRAINT `fk_Peliculas_has_Actores_Peliculas`
    FOREIGN KEY (`Peliculas_idPelicula`)
    REFERENCES `peliculasappdb`.`Peliculas` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peliculas_has_Actores_Actores1`
    FOREIGN KEY (`Actores_idActor`)
    REFERENCES `peliculasappdb`.`Actores` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
